[build]
  command = "npm run build"
  publish = ".next"
  edge_functions = "edge-functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable the problematic plugin that's causing the 404 error
[[plugins]]
  package = "netlify-plugin-no-more-404"
  [plugins.inputs]
    on404 = "warn"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "https://www.devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://devsouth.us"

[dev]
  framework = "next"
  targetPort = 3000
  port = 8888
  command = "npm run dev"
  publish = ".next"
  autoLaunch = true
  debug = false
  functionsPort = 9999
  live = true
  environment = { NODE_ENV = "development" }


