[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    debug = false
    sendSlicesInResponse = true
    incrementalCache = true

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]
  
  # Adjust function settings
  [functions.api]
    external_node_modules = ["next"]
    included_files = [".next/server/**", ".next/standalone/**"]

  # Increase memory allocation
  [functions."*"]
    memory = 8192 # Set to 8GB
    timeout = 30 # Increase timeout to 30 seconds

[[redirects]]
  from = "https://devsouth.us/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sanfordev.com/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sanfordev.io/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sanfordev.net/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true