[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "/tmp/sharp"
  NEXT_PUBLIC_URL = "https://devsouth.us"
  NODE_OPTIONS = "--max-old-space-size=8192"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]
  external_node_modules = ["sharp"]

  [functions.api]
    included_files = [".next/server/**", ".next/standalone/**"]
    environment = { NODE_ENV = "production", NEXT_RUNTIME = "edge" }

  [functions."*"]
    memory = 8192 # 8GB memory
    timeout = 30  # 30 second timeout

# Performance optimizations for assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "https://www.devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[context.production.environment]
NEXT_PUBLIC_SITE_URL = "https://devsouth.us"

