[build]
  command = "npm run netlify-build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "/tmp/sharp"
  NEXT_PUBLIC_URL = "http://localhost:8888"
  NODE_OPTIONS = "--max-old-space-size=8192"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PLATFORM_AGNOSTIC = "1"
  NEXT_IGNORE_CPU_ARCH = "1"
  NEXT_FORCE_SWC_TRANSFORMS = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]
  external_node_modules = ["sharp"]

  [functions.api]
    included_files = [".next/server/**", ".next/standalone/**"]
    environment = { NODE_ENV = "production", NEXT_RUNTIME = "edge" }
    timeout = 60

  [functions."*"]
    memory = 8192
    timeout = 60

  [functions.next-server]
    timeout = 60
    memory = 8192  # Increase memory allocation
    included_files = [".next/server/**", ".next/standalone/**"]
    environment = { NODE_ENV = "production", NEXT_RUNTIME = "edge" }

# Performance optimizations for assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "https://www.devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.devsouth.us/*"
  to = "https://devsouth.us/:splat"
  status = 301
  force = true

[context.production.environment]
NEXT_PUBLIC_SITE_URL = "https://devsouth.us"

[dev]
  framework = "next"
  targetPort = 3000  # Changed from targetPort to target-port
  port = 8888
  command = "npm run dev"
  publish = ".next"
  autoLaunch = true
  debug = false  # Change to false to reduce noise
  watchPort = 3000
  functionsPort = 9999  # Add explicit functions port
  live = true  # Enable live reload
  environment = { NODE_ENV = "development" }  # Explicitly set development environment

[[edge_functions]]
  path = "/*"
  function = "next-server"


