[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  # Enable build caching for faster builds
  NEXT_TELEMETRY_DISABLED = "1"

# Function settings with enhanced performance
[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]
  
  [functions.api]
    external_node_modules = ["next"]
    included_files = [".next/server/**", ".next/standalone/**"]

  [functions."*"]
    memory = 8192 # 8GB memory
    timeout = 30  # 30 second timeout

# Performance optimizations for assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from = "https://devsouth.us/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sanfordev.com/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sanfordev.io/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sanfordev.net/*"
  to = "https://sanfor.dev/:splat"
  status = 301
  force = true

# Fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}